### PR TITLE
Support for recursive extends

### PR DESCRIPTION
**Pull request by josephfinlayson**
Hiya! This is a messy pullrequest, and will be fixed if you like the concept. I want to use extends recursively

I.e. like this:

Given a layout at `layout.html`:
```html
<div>
  <block name="content">templatecontent</block>
</div>
```
and some sort of other component at `card.html`:

```html
<div>
    <block name="cardTitle">cardtemplatecontent</block>
</div>
```

I'd like to have the ability to extend them in each other
```html
<extends src='layout.html'>
  <block name='content'>
    <p>extended content</p>
    <extends src="card.html">
      <block name="cardTitle">
        <p>extended card content</p>
      </block>
    </extends>
  </block>
</extends>
```

Do you like this idea? If so I will fix it up and write comprehensive tests

### CODE REVIEW

**Comment by jescalan** [comment]
Hey, wow I'm so sorry for the super late response here - this one seems to have slipped through the cracks for me. I really like this idea though and feel like this should be merged. The only things I'd love to see updated are:

1. Code formatting changes reverted, only change the pieces that need to be changed (the `handleExtendsNodes` call)
2. A test to verify that nested templates are working 😁 

Is there any chance you'd be willing to make these updates? If so we can get this merged and shipped out.

**Comment by josephfinlayson** [comment]
@jescalan  - yes I will have a fix of these things, it will take a bit of time as I'm now out of the loop, and no longer using Reshape

**Comment by HoldYourWaffle** [comment]
I need this feature in my project, and I would be interested in making the adjustments if @josephfinlayson can't/doesn't want to anymore.

**Comment by josephfinlayson** [comment]
@HoldYourWaffle  - be my guest. I'm sorry I didn't have enough time to commit to this

**Pull request closed without merging**
